Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -14,6 +14,8 @@ jobs:
           norminette 
           if [ $? -ne 0 ]; then 
           echo "norminette not correctly"
+          else 
+          echo "error our not error $?"
           fi
       - name: Check out repository code
         uses: actions/checkout@v4
